---
title: "Power Simulation"
author: "Kathryn Denning"
date: "8/28/2020"
output: html_document
---

```{r setup, echo = FALSE, warning = FALSE, message = FALSE, error = FALSE}
#install.packages("tidyverse")
#install.packages("simr")
#install.packages("lme4")
#install.packages("lmerTest")
#instal.packages("magrittr")
library(tidyverse)
library(simr)
library(lme4)
library(lmerTest)
library(magrittr)
#Setting global chunk options
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)
```

Based on tutorial I found: https://benwhalley.github.io/just-enough-r/power-analysis.html

```{r simulation data}
set.seed(1234)
simulated.df <- data_frame(
  inout_sim = rep(0:1, each = 19,  times = 375),
  issue_sim = rep(0:2, each = 19, times = 250),
  item_num = rep(1:19, 750),
  proj_score = runif(n = 14250, min = 1, max = 6),
  stereo_score = runif(n = 14250, min = 1, max = 6),
  mod = rep(1:5, length.out = 14250),
  targ_item = runif(n = 14250, min = 1, max = 6),
  subject = rep(1:750, each = 19)
)#had to simulate the data off of 19 for the number of items in the BFI, which is why its an odd number and wanted each cell to have at least 50, so this is what we ended up with
head(simulated.df)

simulated.df %<>% 
  mutate(inout_sim = as.factor(inout_sim),
         issue_sim = as.factor(issue_sim))
```



```{r model with no set effect size}
total_model <- lmer(targ_item ~ proj_score*stereo_score*issue_sim*inout_sim*mod + (stereo_score + proj_score|subject), data = simulated.df)
anova(total_model)

```
#model failed to converge at 750, at 600 it had a singularity issue

```{r running simulation with the projection*group effect}
fixef(total_model)['proj_score:inout_sim'] <- 0.36

fixef(total_model)['proj_score'] <- 0.15

powerSim(total_model, test = "proj_score", nsim = 100)
```



